### ISSUE TITLE
waitpid() issue?

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#117]
while working on glib2 testcases I get a lot errors like:

(./gvariant.exe:49046): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.

GLib:ERROR:E:/Trees/glib2/git/glib/tests/gvariant.c:2841:do_failed_test: child process (/gvariant/varargs/subprocess/empty-array [49049]) did not fail as expected

Killed by SIGABRT
pid=0xbf96 ppid=0xbf95 tid=0x0001 slot=0x00b4 pri=0x0200 mc=0x0001 ps=0x0010
E:\TREES\GLIB2\BUILD\GLIB\TESTS\GVARIANT.EXE

steps to reproduce:
- clone glib2
- autoreconf it
- run configure with:
``
LDFLAGS="-Zhigh-mem -Zomf -Zargs-wild -Zargs-resp"
LIBS="-lpthread -lcx"
CFLAGS="-I/@unixroot/usr/include/bind9"
export CFLAGS LDFLAGS LIBS
#export VENDOR="%{vendor}"
../git/configure \
    --enable-shared --disable-static \
    --with-pcre=system \
--program-prefix= --prefix=/@unixroot/usr --exec-prefix=/@unixroot/usr --bindir=/@unixroot/usr/bin \
--sbindir=/@unixroot/usr/sbin --sysconfdir=/@unixroot/etc --datadir=/@unixroot/usr/share \
--includedir=/@unixroot/usr/include --libdir=/@unixroot/usr/lib --libexecdir=/@unixroot/usr/libexec \
--localstatedir=/@unixroot/var --sharedstatedir=/@unixroot/usr/com --mandir=/@unixroot/usr/share/man \
--infodir=/@unixroot/usr/share/info >build.log
``

- add build\glib\.libs dir to beginlibpath (needed so it uses the built glib20.dll for internal stuff)
- make
- then either add all .libs subdir to beginlibpath, or copy the 4 dll to a single location and add only this location to it
- got to build\glib\tests directory
- make gvariant.exe
- execute gvariant.exe

this should give a trp file and the above message

**Comment by dmik** [comment]
Can confirm that.

**Comment by dmik** [comment]
According to my tests, this has nothing to do with LIBC, it's a Glib guilt. Will create a ticket.

**Comment by dmik** [comment]
Closing this as nothing to fix.
