### ISSUE TITLE
Make stat succeed on file names with trailing spaces

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libc#12]
OS/2 ignores trailing space characters in file names and behaves as if file names were given w/o them. This, in particular, means that that all of:
```
cmd /c echo test > "test.txt"
cmd /c echo test > "test.txt "
```
will write to the same file. As well as:
```
cmd /c dir "test.txt" "test.txt "
```
will list the same file.

Note that `stat` in IBM VisualAge C behaves like that: it ignores trailing spaces in file names. So does OpenWatcom 1.9.

The test case is trivial (given it's saved in `space.cpp`):
``` c++
#include <stdio.h>
#include <sys/stat.h>

int main ()
{
  struct stat st;
  int rc = stat ("space.cpp ", & st);
  printf ("stat rc %d\n", rc);
  return 0;
} 
```

Note that leading spaces are not stripped off — they are valid characters of the file name.

Discovered when working on https://github.com/bitwiseworks/qtbase-os2/issues/49.

**Comment by dmik** [comment]
Note that this is another showstopper for https://github.com/bitwiseworks/qtbase-os2/issues/29.

**Comment by dmik** [comment]
The reason of the failures is the `fsResolveUnix` implementation in `liub/sys/fs.c`. It's code is *really* complex and it uses `DosFindFirst/DosFindNext` to resolve/verify the file path. Seems that it was done so to obtain real file casing.

DosFindFirst accepts spaces just fine but of course it returns `space.cpp` when `space.cpp ` is requested. Even further, kLIBC appends ? to the name of the file, as the comments say, "for getting casting resolved" (although my tests show that wildcards are not necessary there — it works for a plain file name as well).

If, howver, ? follows a space char (i.e. `space.cpp ?`, not `space.cpp?`), then DosFindFirst immediately returns ERROR_NO_MORE_FILES which causes fsResolveUnix to bail out with ENOENT and for this reason the `stat` call doesn't even proceed further (because it first tries to resolve the file name).

I need to think how to best fix this.

**Comment by dmik** [comment]
BTW, if you compile with `-Zno-unix`, this will make `fsResolveOS2` to be used instead and that one does not do any DosFindFirst magic, it just converts slashes. So with this flag, `stat` for `space.cpp ` works well (expectedly). This isn't a solution for our problem of course because `-Zno-unix` disables all Unix extensions including symlinks which is simply a no go.

**Comment by dmik** [comment]
I simply dropped the wildcard part in my fix above and all seems work now, including the case with spaces. I will have the new kLIBC run locally for a while to check for possible regressions.

**Comment by dmik** [comment]
Note that the exact reason why Knut decided to use the wildcard is not known. May be it's FS driver dependent and doesn't work on HPFS/FAT etc. But as we generally don't officially support anything but JFS anyway, we will leave it as it is — at least until we get a failing case that is important to get it fixed.

**Comment by psmedley** [comment]
Hi - is there a build of libc066.dll with this fix available? latest in rpm is 6JUN18
