### ISSUE TITLE
libc_dll.a: Undefined symbol _touch referenced from text segment

### ISSUE THREAD

**Issue by gp-Digi** [bitwiseworks/libc#133]
After updating libc, I get the following errors when building projects:

>make
D:/usr/bin/../lib/gcc/i686-pc-os2-emx/9/../../../libc_dll.a(recv.o): Undefined symbol _touch referenced from text segment
D:/usr/bin/../lib/gcc/i686-pc-os2-emx/9/../../../libc_dll.a(recvfrom.o): Undefined symbol _touch referenced from text segment

**Comment by SilvanScherrer** [comment]
did you update via rpm? as latest libc needs a new libsocket as well.  whats the date of your libc_dll.a and libsocket.lib

**Comment by dmik** [comment]
JFTR, the problem was the fact that libsocket is actually a **static** lib of wrappers around TCPIP32.DLL, i.e. these wrappers are not part of LIBC DLL. So the problem did not pop up at LIBC compile time. Fixed by explicitly exporting `__libc_toucn` from LIBC DLL.
