### ISSUE TITLE
remove() not working on directories

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#138]
https://github.com/bitwiseworks/libc/blob/master/src/emx/src/lib/io/remove.c only works for files. But this is wrong. Even Knut stated it should work for Directories as well. But it misses the fsDirRemover() part when its a Directory.

**Comment by dmik** [comment]
Yes, you are right. This is a POSIX requirement indeed, https://pubs.opengroup.org/onlinepubs/007904975/functions/remove.html.
