### ISSUE TITLE
Fix default shell location in paths.h and in processGetDefaultShell

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#15]
it still searches sh in /@unixroot/bin which is completely wrong, as we eliminated the /bin path since long.
see also http://trac.netlabs.org/libc/ticket/371

I know there is a os2-base-fhs rpm which sets a symlink, but as we don't set that as required, we should change libc.

**Comment by dmik** [comment]
Note that we also should change all `/@unixroot/[s]bin` entries to `/@unixroot/usr/[s]bin` in `paths.h`. And remove a sed entry from `libc.spec` that does that at RPM build time (only for `/usr/bin` paths).
