### ISSUE TITLE
Strange crashes in PMMail with libcno.dll

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/libc#33]
I have been using the new libcno.dll and everything except PMMail seems to work fine. With PMMail I will sometimes have it disappear from the screen (usually when sending a large file), or trap (usually when indexing or trying to view a folder with a lot (3000) of files. Here is a typical example:
______________________________________________________________________

 Exception Report - created 2019/02/22 16:35:00
______________________________________________________________________

 3.22.00.2301

 OS2/eCS Version:  2.45
 # of Processors:  4
 Physical Memory:  3005 mb
 Virt Addr Limit:  2560 mb
 Exceptq Version:  7.11.3-shl (Jul  5 2016)

______________________________________________________________________

 Exception C0000005 - Access Violation
______________________________________________________________________

 Process:  C:\PROGRAMS\PMMAIL\BIN\PMMAIL.EXE (11/23/2016 06:24:14 1,817,288)
 PID:      5B (91)
 TID:      03 (3)
 Slot:     91 (145)
 Priority: 200

 Module:   LIBCN0
 Filename: C:\USR\LIB\LIBCN0.DLL (02/15/2019 09:26:22 1,158,654)
 Address:  005B:1EE17186 (0001:00087186)
 Cause:    Attempted to read from 801EE170
           (unallocated memory)

______________________________________________________________________

 Failing Instruction
______________________________________________________________________

 1EE17177  MOV  EBX, [ESI-0x4]   (8b5e fc)
 1EE1717A  TEST BL, 0x3          (f6c3 03)
 1EE1717D  JZ   0x1ee173a3       (0f84 20020000)
 1EE17183  AND  EBX, -0x8        (83e3 f8)
 1EE17186 >MOV  EDX, [EBX]       (8b13)
 1EE17188  CMP  EDX, 0xdd63eeed  (81fa edee63dd)
 1EE1718E  JZ   0x1ee171e4       (74 54)
 1EE17190  CMP  EDX, 0xdd73eeed  (81fa edee73dd)

______________________________________________________________________

 Registers
______________________________________________________________________

 EAX : 00000001   EBX  : 801EE170   ECX : 00000000   EDX  : 02B278B1
 ESI : 211C5378   EDI  : 02EFB4E0
 ESP : 02B275FC   EBP  : 02B27644   EIP : 1EE17186   EFLG : 00010282
 CS  : 005B       CSLIM: FFFFFFFF   SS  : 0053       SSLIM: FFFFFFFF

 EAX : not a valid address
 EBX : unallocated memory
 ECX : not a valid address
 EDX : read/write memory on this thread's stack
 ESI : read/write memory allocated by LIBCN0
 EDI : read/write memory allocated by PMMERGE

______________________________________________________________________

 Stack Info for Thread 03
______________________________________________________________________

   Size       Base        ESP         Max         Top
 00008000   02B28000 -> 02B275FC -> 02B24000 -> 02B20000

______________________________________________________________________

 Call Stack
______________________________________________________________________

   EBP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 Trap  ->  1EE17186   LIBCN0    0001:00087186  ifree.c#134 __um_free_maybe_lock + 22 0001:00087164 (ifree.obj)

  Offset Name                 Type                         Hex Value
  ────── ──────────────────── ──────────────────────────── ─────────
   8     block                pointer to void              211C5378
   12    lock                 32 bit signed                1

 02B27644  1EDFA7A9   LIBCN0    0001:0006A7A9  free.c#19 __std_free + 19 0001:0006A790 (free.obj)

  Offset Name                 Type                         Hex Value
  ────── ──────────────────── ──────────────────────────── ─────────
   8     block                pointer to void              211C5378

 02B27664  000E3BE3   PMMAIL    0001:000D3BE3  between UtilsStrReplace + 1F and UtilsStrdup - 65

 02B27694  00069BD0   PMMAIL    0001:00059BD0  between FolderReindexAllAbort + 1760 and FolderReindexThread - 504

 02B27F74  0006A05A   PMMAIL    0001:0005A05A  between FolderReindexAllAbort + 1BEA and FolderReindexThread - 7A

 02B27FB4  1EDDF4CE   LIBCN0    0001:0004F4CE  beginthr.c#38 ___libc_back_threadCreate - 6A 0001:0004F538 (beginthr.obj)

 02B27FF4  1FFECE38   DOSCALL1  0004:0000CE38  DOS32R3EXITADDR

______________________________________________________________________

 Labels on the Stack
______________________________________________________________________

   ESP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 02B27634  1ED9D737   LIBCN0    0001:0000D737  fmutex.c#439 ___fmutex_release_internal + 4B 0001:0000D6EC (D:\Users\dmik\rpmbuild\BUILD\libc-0.1.0\src\emx\src\lib\process\fmutex.c)
 02B27648  1EDFA7A9   LIBCN0    0001:0006A7A9  free.c#19 __std_free + 19 0001:0006A790 (free.obj)
 02B27654  000E4127   PMMAIL    0001:000D4127  between UtilsFormatTimeDiff + AF and UtilsFormatMsgSize - 11
 02B27668  000E3BE3   PMMAIL    0001:000D3BE3  between UtilsStrReplace + 1F and UtilsStrdup - 65
 02B27678  1EE0BAAA   LIBCN0    0001:0007BAAA  stat.c#24 __std_stat + 7A 0001:0007BA30 (stat.obj)
 02B27698  00069BD0   PMMAIL    0001:00059BD0  between FolderReindexAllAbort + 1760 and FolderReindexThread - 504
 02B27730  000A9EC0   PMMAIL    0001:00099EC0  between ReadwinAttachmentSave + 820 and ReadWinOpenInBrowser - FB4
 02B27738  000A9EC0   PMMAIL    0001:00099EC0  between ReadwinAttachmentSave + 820 and ReadWinOpenInBrowser - FB4
 02B27C88  1FC3EB35   PMMERGE   0004:000FEB35 
 02B27C90  1FC42C04   PMMERGE   0004:00102C04 
 02B27C94  1FC42C2E   PMMERGE   0004:00102C2E 
 02B27C98  1FC51743   PMMERGE   0004:00111743 
 02B27C9C  1FC3EB35   PMMERGE   0004:000FEB35 
 02B27CA4  1FC42C04   PMMERGE   0004:00102C04 
 02B27CB4  914237C7   OBJDTAHK  0001:000037C7 
 02B27CD4  9EAD083F   XWPHOOK   0002:0000083F  between hookSetGlobalHotkeys + 29D and GetFrameWindow - 444
 02B27CF4  1FC6A7BB   PMMERGE   0004:0012A7BB 
 02B27D0C  9ECE1CD0   OBJDCOMN  0001:00001CD0 
 02B27D20  1FC42F51   PMMERGE   0004:00102F51 
 02B27D2C  1FC8BE84   PMMERGE   0004:0014BE84 
 02B27D40  1FC8C100   PMMERGE   0004:0014C100 
 02B27D48  1FC8BE02   PMMERGE   0004:0014BE02 
 02B27D68  1FC4206F   PMMERGE   0004:0010206F 
 02B27D7C  1EEC660C   LIBC066   0001:0001660C 
 02B27D80  1EEC6688   LIBC066   0001:00016688 
 02B27E4C  1EEC6620   LIBC066   0001:00016620 
 02B27ED8  000E7A44   PMMAIL    0001:000D7A44  between rbt_lookup + 194 and __ZNSt15basic_streambufIcSt11char_traitsIcEE13_S_pback_sizeE$w$kOTwkuMIMd7fr9c00 - 960
 02B27F18  000E7777   PMMAIL    0001:000D7777  between rbt_insert + 1B and rbt_search - 15
 02B27F38  00126771   PMMAIL    0001:00116771  between OSWinThreadSetInsert + 5D and OSWinThreadSetRemove - 2F
 02B27F58  0012667C   PMMAIL    0001:0011667C  between OSWinThreadEntry + 34 and OSWinThreadExit - 20
 02B27F78  0006A05A   PMMAIL    0001:0005A05A  between FolderReindexAllAbort + 1BEA and FolderReindexThread - 7A
 02B27FA0  9DE11270   EXCEPTQ   0001:00001270  MYHANDLER  (in exceptq.c)
 02B27FB8  1EDDF4CE   LIBCN0    0001:0004F4CE  beginthr.c#38 ___libc_back_threadCreate - 6A 0001:0004F538 (beginthr.obj)
 02B27FD8  1EDEEE00   LIBCN0    0001:0005EE00  exceptions.c#74 __libc_Back_exceptionHandler 0001:0005EE00 (exceptions.obj)
 02B27FF8  1FFECE38   DOSCALL1  0004:0000CE38  DOS32R3EXITADDR
------------------------------------------------------------------------------------------------------------

 (Can't seem to attach a file...) No idea if this is PMMails' fault or libc, but if I put the last version of libc066.dll (and the libc063 forwarder) in the PMMail binary directory and start libpathstrict using RUN!, it works fine again.

**Comment by dmik** [comment]
Are you sure the previous build of LIBC (i.e. a "normal" libc066.dll with size > 1M) doesn't crash like that? What puzzles me is how LIBC ends up in PMMAIL at all. Is it some fresh build of it built with GCC?

**Comment by dmik** [comment]
Judging by the trap report, LIBC fails because some invalid (may be already freed) address (0x 211C5378) is passed down to LIBC's `free`.

**Comment by DavidMcKenna** [comment]
PMMail version 3.22.00.2301 from Nov 2016, the publicly available one. Never had this issue before installing libcn0.dll (been using PMMail for years), and don't now that I am running with the last version of libc066.dll (and libc063.dll forwarder) libpathstrict. PMDLL does show PMMail linked to libc063.dll....

**Comment by rbri** [comment]
Same here, PMMail failed from time to time. But starting today it fails reproducible at startup. Will attach the trap file.

**Comment by rbri** [comment]
Trap file

**Comment by Greggk** [comment]
I see this also. However the libcn0.dll while a necessary condition for this problem it isn't a sufficient condition. The mail folder being scanned must contain a "poorly formed" message. I found this by removing messages from my inbox. It isn't the number of messages that causes it as I have folders with 4-5 times the number in my onbox that work fine. I have yet to find the exact message but I think it may have something to do with the "From" field. I have built PMMail against libcn0.dll and libcx.dll (0.65) using GCC 4.9.2 and that fixes this issue. I tried with GCC 8.3.0 which corrupts all "From" fields (blank or garbage characters). Perhaps a pointer to already freed memory.  I am working with Voice to get a new PMMail release out to fix this issue. 

Note: PMMail has been built with GCC 3.3.5 for a very long time. So its use of libc isn't new. The current release was built against version 0.6.3. I will see if I can find a likely source for a double free.

Workarounds:
1. Revert to libc 6.6 for PMMail (libc 0.6.3 forwarder)
2. Find and remove bad messages from your mail store.

**Comment by rbri** [comment]
Great, thanks a lot.

On Tue, 21 May 2019 11:48:36 -0700 Greggk wrote:
>
>I see this also. However the libcn0.dll while a necessary condition for this problem it isn't a sufficient condition. The mail folder being scanned must contain a "poorly formed" 
message. I found this by removing messages from my inbox. It isn't the 
>number of messages that causes it as I have folders with 4-5 times the number in my onbox that work fine. I have yet to find the exact message but I think it may have something to 
do with the "From" field. I have built PMMail against libcn0.dll 
>and libcx.dll (0.65) using GCC 4.9.2 and that fixes this issue. I tried with GCC 8.3.0 which corrupts all "From" fields (blank or garbage characters). Perhaps a pointer to already freed 
memory.  I am working with Voice to get a new PMMail release 
>out to fix this issue. 
>
>Note: PMMail has been built with GCC 3.3.5 for a very long time. So its use of libc isn't new. The current release was built against version 0.6.3. I will see if I can find a likely source 
for a double free.
>
>Workarounds:
>1. Revert to libc 6.6 for PMMail (libc 0.6.3 forwarder)
>2. Find and remove bad messages from your mail store.
>

**Comment by rbri** [comment]
Any progress? The alpha version available as download is in-between outdated.

**Comment by SilvanScherrer** [comment]
If you refer to PMMail progress you need to ask Voice or whoever is responsible for that. As for libcn we have no time to look into it right now, as all our power goes into Qt 5. And until now it's just PMMail which we know has issues.

**Comment by rbri** [comment]
Thanks for the clarification - will try to contact Voice.

**Comment by DavidMcKenna** [comment]
No longer an issue with the new PMMail.

**Comment by SilvanScherrer** [comment]
Great thx for letting us know.

**Comment by rbri** [comment]
> No longer an issue with the new PMMail.

Same here, thanks for your ongoing support.
