### ISSUE TITLE
not preserving cases on casesensitive directories

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#39]
When walking through a dir with opendir() readdir() on a JFS drive all files are shown like they should and cases of filenames are preserved. When running the same opendir() readdir() from a DVD drive the filenames are all lowercase.

**To Reproduce**
build the below snippet and run it from a JFS drive and from a DVD drive.
```
#include <stdio.h>
#include <string.h>
#include <dirent.h>

void main(void)
{

    DIR *dirp;
    struct dirent *dp;
    char *dirname = "/@unixroot/usr/lib/python2.7";
    char *nameWithExt = "UserDict.py";
    int namelen = 8;

    /* Open the directory and search the entries for an exact match. */
    dirp = opendir(dirname);
    if (dirp) {
        while ((dp = readdir(dirp)) != NULL) {
            const int thislen = strlen(dp->d_name);
            printf("bww trace thislen: %i d_name: %s\n", thislen, dp->d_name);
            if (thislen >= namelen &&
                strcmp(dp->d_name, nameWithExt) == 0) {
                (void)closedir(dirp);
                return; /* Found */
            }
        }
        (void)closedir(dirp);
    }
    return; /* Not found */
}
```

**Expected behavior**
It should work always the same.

**Reason**
the following call stack is used opendir() -> getdirent() -> _fnlwr2() -> _fngetdrive()
as _fngetdrive returns 0, is uses the curdrive to figure out the case. This is completely wrong.

**Proposal**
change _fnlwr2() in emx/src/lib/misc to either not translate stuff from /@unixroot, or get the drive from the UNIXROOT end in case the dir starts with /@unixroot.

**Comment by dmik** [comment]
Good catch @SilvanScherrer, thanks!
