### ISSUE TITLE
select()

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#42]
our select() is really flaky, at least when it comes to asynchronous connect(). in cups they use this and select() does imho stange things. I had to disable FD_ISSET() completely and use getpeername() instead. This works.

To me it seems like some sockets are not cleared in case of errors and so FD_ISSET() works even it should not.
see https://github.com/bitwiseworks/cups-os2/commit/2b26941e54ad30810f70b5cfc84b98224ae3a626 for the change I had to do

**Comment by dmik** [comment]
I've dug into it. What I found is that the code in `cups/http-adddrlist.c` is simply broken (does not correspond to the the `connect` manpage). While kLIBC, in turn, seems to behave correctly.

1. The CUPS code checks if the socket is ready for **reading**, while according to e.g. http://man7.org/linux/man-pages/man2/connect.2.html it should wait for **writing** (a similar clause is contained in a similar https://man.openbsd.org/connect.2):
```
EINPROGRESS
              The socket is nonblocking and the connection cannot be
              completed immediately.  (UNIX domain sockets failed with
              EAGAIN instead.)  It is possible to select(2) or poll(2) for
              completion by selecting the socket for writing.  After
              select(2) indicates writability, use getsockopt(2) to read the
              SO_ERROR option at level SOL_SOCKET to determine whether
              connect() completed successfully (SO_ERROR is zero) or
              unsuccessfully (SO_ERROR is one of the usual error codes
              listed here, explaining the reason for the failure).
```
2. The CUPS code does **not** call `getsockopt` to fetch the actual async result of `connect` (also from the man page above).
3. There is some info that even if SO_ERROR is zero, it doesn't mean that the connection was already established, see a comment in https://stackoverflow.com/questions/17769964/linux-sockets-non-blocking-connect:
> When getsockopt(fd, SOL_SOCKET, SO_ERROR, ...) returns 0, with 0 in so_error, this does not mean that the socket is connected. This means no error occured until now. In this specific case, you need to call getpeername() and if getpeername() returns 0, this means the socket is connected. If the socket is not connected, getpeername() returns -1 with ENOTCONN in errno. getsockopt(fd, SOL_SOCKET, SO_ERROR, ...) can inform you about a connection refused, but not about a connected socket. You need to use getpeername() or other means to be sure the socket is connected. – Alexandre Fenyo Dec 12 '18 at 19:49

So a call to `getpeername` as a final test is needed anyway.

I modified the code according to the above, and it seems to work smoothly. Please check.

Note that I've also disabled the workaround from the commit above as it's not needed anyway.
