### ISSUE TITLE
struct stat lacks st_mtimensec and friends in BSD mode

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libc#45]
It appears that `sys/stat.h` does not define macros to access the nanoseconds field of the `stat` structure when the program is built in _BSD_SOURCE mode (which is default in kLIBC). There are correct `st_mtime` etc defines, but no `st_mtimensec`. See https://github.com/freebsd/freebsd/blob/master/sys/sys/stat.h for how it should be. I.e. we lack this next to `#define st_mtime` and friends:
```
#define	st_atimensec		st_atimespec.tv_nsec
#define	st_mtimensec		st_mtimespec.tv_nsec
#define	st_ctimensec		st_ctimespec.tv_nsec
#define	st_birthtimensec	st_birthtimespec.tv_nsec
```

Note that we might also want to add `st_mtim` which is an alias to `st_mtimespec` used in the struct as this is what other platforms seem to have — for more details, check https://github.com/bitwiseworks/qtwebengine-chromium-os2/blob/98a39084cd5fb5aabb04585b51b35cc524cf5b23/ninja/src/disk_interface.cc#L208 where this ticket's problem was discovered in the first place.

A workaround (until a new RPM is released) is as trivial as definig the above defines where they are needed.

**Comment by SilvanScherrer** [comment]
dash configure.ac also uses the following snippet:
```
dnl Check if struct stat has st_mtim.
AC_MSG_CHECKING(for stat::st_mtim)
AC_COMPILE_IFELSE(
[AC_LANG_PROGRAM([#include <time.h>
#include <sys/time.h>
#include <sys/stat.h>],
[struct stat foo; return sizeof(foo.st_mtim.tv_sec)])],
have_st_mtim=yes, have_st_mtim=no)
AC_MSG_RESULT($have_st_mtim)
if test "$have_st_mtim" = "yes"; then
	AC_DEFINE([HAVE_ST_MTIM], [1],
		[Define if your `struct stat' has `st_mtim'])
fi
```

**Comment by dmik** [comment]
Note that in case of `st_mtim` and friends the above commit does quite the opposite to what FreeBSD headers do. They define `st_mtim` as a real `struct stat` field and define `stmtimespec` as an alias for it. Our LIBC uses `st_mtimespec` as a real field name and I decided that it's safer not to change it in `struct_stat`but instead define `st_mtim` as an alias for that. This way we will certainly **not** break any older OS/2 code that might rely on that. And for new code both approaches should be identical. If, however, we find a case where they are not, we might want to reconsider.

**Comment by dmik** [comment]
In the way it is, it causes build problems in Qt 5. The error is as follows:
```
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:274:1: error: redefinition of 'template<class T> typename std::enable_if<((& T::st_atimespec), true), long long int>::type {anonymous}::GetFileTimes::atime(const T&, int)'
  274 | atime(const T &statBuffer, int)
      | ^~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:252:1: note: 'template<class T> typename std::enable_if<((& T::st_atimespec), true), long long int>::type {anonymous}::GetFileTimes::atime(const T&, int)' previously declared here
  252 | atime(const T &statBuffer, int)
      | ^~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:279:1: error: redefinition of 'template<class T> typename std::enable_if<((& T::st_birthtimespec), true), long long int>::type {anonymous}::GetFileTimes::birthtime(const T&, int)'
  279 | birthtime(const T &statBuffer, int)
      | ^~~~~~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:257:1: note: 'template<class T> typename std::enable_if<((& T::st_birthtimespec), true), long long int>::type {anonymous}::GetFileTimes::birthtime(const T&, int)' previously declared here
  257 | birthtime(const T &statBuffer, int)
      | ^~~~~~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:284:1: error: redefinition of 'template<class T> typename std::enable_if<((& T::st_ctimespec), true), long long int>::type {anonymous}::GetFileTimes::ctime(const T&, int)'
  284 | ctime(const T &statBuffer, int)
      | ^~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:262:1: note: 'template<class T> typename std::enable_if<((& T::st_ctimespec), true), long long int>::type {anonymous}::GetFileTimes::ctime(const T&, int)' previously declared here
  262 | ctime(const T &statBuffer, int)
      | ^~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:289:1: error: redefinition of 'template<class T> typename std::enable_if<((& T::st_mtimespec), true), long long int>::type {anonymous}::GetFileTimes::mtime(const T&, int)'
  289 | mtime(const T &statBuffer, int)
      | ^~~~~
D:/Coding/qt5/qt5/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:267:1: note: 'template<class T> typename std::enable_if<((& T::st_mtimespec), true), long long int>::type {anonymous}::GetFileTimes::mtime(const T&, int)' previously declared here
  267 | mtime(const T &statBuffer, int)
      | ^~~~~
```
The reason is the following. Qt assumes that `st_mtim` (and friends) is either a real member of `struct stat` (i.e. not a define) or doesn't exist at all (in which case `mtime` is not defined). For `st_mtimespec` (and friends) it assumes that it might be a define and only define `mtime` if its not and if it exists. 

However, in our LIBC it's the other way around and we get duplicate definitions of `mtime`. The first one is through `st_mitim` (Qt doesn't check that it's a macro and it gets replaced with `st_mtimespec` which exists and causes the define to get triggered). The second one is through `st_mtimespec` which is not define in our LIBC and does exist.

Strictly speaking, the Qt code is not very correct as it doesn't cover all possible combinations. They simply assume that every platform follows POSIX.1-2008 nowadays and provides fallbacks via defines to old code, not the other way around. So I can fix this problem in two ways:

1. In Qt by checking if `st_mtim` is a define (just like they do for `st_mtimespec`)
2. In LIBCn, by making `st_mitim` the real struct member name (as per POSIX) and turning `st_mitimespec` into a define.

1 is simpler but 2 appears to be more correct (as makes things POSIX-compilant) though I'm not sure if there are OS/2 apps that it will break.

**Comment by dmik** [comment]
I've swapped the definitions to match POSIX. Qt5 is happy now. We will leave it so for the time being and look for any breaks in legacy OS/2 software (note that it may show up only on source level, i.e. when compiling, so this is highly unlikely).
