### ISSUE TITLE
sigprocmask

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#50]
emx/src/lib/process/sigprocmask.c returns -1 if iHow value is not valid. According to posix it should return errno.

**Comment by dmik** [comment]
According to which Posix? This page https://pubs.opengroup.org/onlinepubs/7908799/xsh/sigprocmask.html says it should return -1 on any failure and set `errno` to the error. http://man7.org/linux/man-pages/man2/sigprocmask.2.html says just the same.

**Comment by SilvanScherrer** [comment]
Yes you are right. I mixed it up with http://man7.org/linux/man-pages/man3/pthread_sigmask.3.html. so its a pthread issue.
