### ISSUE TITLE
semaphore.h

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libc#54]
we also miss the semaphore handling which is a posix feature. @komh did a nice implementation in ht https://github.com/komh/os2compat/tree/master/thread

**Comment by dmik** [comment]
I also stumbled upon it when working on https://github.com/bitwiseworks/qtwebengine-os2/issues/3. I provided a quick implementation of that in-place, but it seems rather easy to do it in general.

Also, my implementation only uses a single OS/2 semaphore (HEV) object and doesn't need two mutex objects — thanks to atomic operations available as GCC builtins.

**Comment by dmik** [comment]
Done and roughly tested. Note that named semaphores (sem_open/sem_close/sem_unlink) are not done yet. One that needs them will have to create a new ticket.
