### ISSUE TITLE
emxomf: Record too long

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libc#74]
From https://github.com/bitwiseworks/qtwebengine-chromium-os2/issues/3#issuecomment-625782732:
> g++ -MMD -MF obj/net/net/http_stream_factory_job.o.d -DUSE_AURA=1 -DNO_TCMALLOC -DCHROMIUM_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DOPENSSL_NO_ASM -DDLOPEN_KERBEROS -DNET_IMPLEMENTATION -DENABLE_BUILT_IN_DNS -DUSE_SYSTEM_ZLIB=1 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -Igen -I../../../../../qt5/qtwebengine/src/3rdparty/chromium -Igen -Igen -Igen -Igen -I../../../../../qt5/qtwebengine/src/3rdparty/chromium/third_party/protobuf/src -Igen/protoc_out -I../../../../../qt5/qtwebengine/src/3rdparty/chromium/third_party/protobuf/src -I../../../../../qt5/qtwebengine/src/3rdparty/chromium/third_party/boringssl/src/include -I../../../../../qt5/qtwebengine/src/3rdparty/chromium/third_party/ced/src -I../../../../../qt5/qtwebengine/src/3rdparty/chromium/third_party/brotli/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -Zomf -m32 -msse2 -mfpmath=sse -mmmx -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-dangling-else -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -O0 -fno-omit-frame-pointer -g2 -std=c++14 -Wno-narrowing -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -fno-exceptions -fno-rtti -c ../../../../../qt5/qtwebengine/src/3rdparty/chromium/net/http/http_stream_factory_job.cc -o obj/net/net/http_stream_factory_job.o
emxomf: Record too long
D:\Temp/ccmqxTwe.s: Assembler messages:
D:\Temp/ccmqxTwe.s: Fatal error: emxomf failed

It fails attempting to write 235 bytes in an OMF record which already has 787 bytes in it. This gives 1022 bytes in total. Since the maximum record size is defined as 1024 bytes (minus 4 bytes for some reason), it fails.

Further digging shows that this happens when writing PUBDEF records. Or, to be more exact, when putting N_TEXT a.out records that (should) fit 16-bit PUBDEF records. I don't remember OMF format details by heart so some more digging is needed.

**Comment by StevenLevine** [comment]
Roderick call, so here's my 0¢ worth...

The -4 accounts for the record type, record size and checksum fields.

Based on what you say, a quick look at  write_pubdef1() indicates that emxomf might not be splitting the PUBDEF records properly.

The code at:

emxomf.c:1320
                if (started && !fits (strlen (name) + 6 + (sym_more[i].hll_type > 127)))
                  {
                    write_rec ();
                    started = FALSE;
                  }

is supposed avoid overflows, but the error indicates that this is not happening.  The variable part of the repeated entries of a PUBDEF record is a max of 7 bytes of the code appears to handle this, but the error says otherwise.

**Comment by dmik** [comment]
Yes, this was also my guess and the secret `-b` switch (that forces writing everything into 32-bit PUBDEF records) proves that: the problem goes away when using it. So now I have to find out why exactly the split (or whatever else) fails.

**Comment by dmik** [comment]
Interestingly enough, this turned out to be my own regression back from 2010 (!). This is the commit that brought it: http://trac.netlabs.org/libc/changeset/3730. My patch was rather big and it fixed a "symbol too long" error when linking Qt 4 DLLs IIRC. Both me and Knut overlooked this tiny check back then.

Anyway, the fix is trivial and it's in now. The real case works too.
