### ISSUE TITLE
emxomfld: extremely slow on too many object files

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libc#83]
Linking the Chromium DLL in Qt 5 (https://github.com/bitwiseworks/qtwebengine-os2/issues/1#issuecomment-646206029) leads to very slow behavior that ends up with the hard hang.

The link command included 3426 object files and 545 static libraries (which in total include around 10 000 object files). It took around 6 hours before `emxomfld` did its work and passed execution to `wl.exe` which just hung (causing a cold reboot).

Most of the time `emxomfld` was spinning in `weakd` code with tons of messages like this:
```
weakld: info: Reading @0x00000000 D:\Coding\qt5\qt5-dev-build\qtwebengine\src\core\debug\obj\third_party\webrtc\common_audio\common_audio_c\ilbc_specific_functions.o
```
before it composed an object file with tons of weak symbols and called `wl.exe` with all the passed object and static library files plus that weak symbols object file. WL hung due to OOM condition, most likely.

Before dealing with OOM in WL, EMXOMFLD should be optimized to speed up weak symbols processing. Even 1 second per object file is way too much: for 15k objects it's more than 4 hours — totally not acceptable. And visually some files take much more than 1 second to get processed.

This ticket is obviously a show stopper for further Chromium development.

**Comment by dmik** [comment]
Note that some comments in emxomfld/weakld sources suggest that there is room for optimizing (i.e. optimizing grow.c that is responsible for the hash table used to keep track of symbols).

Also note that our fork, including the EMX toolchain, is based on the [0.6 branch of kLIBC](http://trac.netlabs.org/libc/log/branches/libc-0.6/src/emx/src/emxomf) while its [trunk version](http://trac.netlabs.org/libc/log/trunk/emx/src/emxomf) contains some commits that look like possible optimizations. Some of these commits were cherry picked and backported to 0.6 but not all. This needs sorting out.

**Comment by dmik** [comment]
This is some weakld statistics from the log, JFYI:
```
weakld: info: cWeakAliases=1487454 cMaxObjExts=14987 cMaxLibExts=9887
```
I've added some profiling code that counts the number of milliseconds WEAKLD spends when parsing OMF files. And with this profiling I see that increasing the hash table size from 211 to 2011 alone gives a significant boost. This is one of the heaviest files among the first ~600 object files with the old has table size (fastest from 3 attempts):
```
weakld: info: adding object D:\Coding\qt5\qt5-dev-build\qtwebengine\src\core\debug\obj\third_party\blink\public\mojo_bindings\mojo_bindings_jumbo_2.o.
weakld: info: Reading @0x00000000 D:\Coding\qt5\qt5-dev-build\qtwebengine\src\core\debug\obj\third_party\blink\public\mojo_bindings\mojo_bindings_jumbo_2.o
*** MSCOUNT: WLDAddObject: 2032 ms
```
And this is with the new size:
```
weakld: info: adding object D:\Coding\qt5\qt5-dev-build\qtwebengine\src\core\debug\obj\third_party\blink\public\mojo_bindings\mojo_bindings_jumbo_2.o.
weakld: info: Reading @0x00000000 D:\Coding\qt5\qt5-dev-build\qtwebengine\src\core\debug\obj\third_party\blink\public\mojo_bindings\mojo_bindings_jumbo_2.o
*** MSCOUNT: WLDAddObject: 387 ms
```
Not bad — more than 5 times faster. And the hash table size increase is not significant. Given that the entry is a pointer (4 bytes), it has grown from ~800 B to just ~8 KB. I will try to increase it further.

I will also try to apply `grow.c` optimizations from the kLIBC trunk to see if it makes any diff.

**Comment by dmik** [comment]
Increasing it to 10007 speeds it up even further — to 227 ms, i.e. 10 times faster. Given that there are 1487454 weak aliases, there must be many million of symbols that are put in the hash table. So it's quite expected that increasing it further will make it faster again. Though there is obviously degradation in speed increase. E.g. increasing the hash size to 99991 makes it as fast as 180 ms — not that much given that memory consumption is increased 10 times (making the table as big as ~400 KB).

However, these are only 600 object files out of 15k. The more files are there, the more effective is the hash table size increase.

**Comment by StevenLevine** [comment]
Bumping the hash table size always helps performance as long you have a
good hashing function.  If you are profiling, you might want to count the
number of hash collisions and hash lookups.  This ratio of these numbers
is good measure of the effectiveness of the hash function.

FWIW, you can speed up the for loops in strpool_addn and strpool_addnu at:

   for (v = p->table[hash]; v != NULL; v = v->next)
    if (strlen (v->string) == len && memcmp (v->string, s, len) == 0)
      return v->string;

by doing the memcmp only if the first characters match.

Another possible speedup is to have strpool_addn and strpool_addnu return
the calculated hash.  This would avoid calculating it twice when
pWld->fFlags & WLDC_CASE_INSENSITIVE is true.

**Comment by dmik** [comment]
Optimized `grow.c` (that avoids repetitive `strlen` calls for each hash table add operation) also gives some nice boost! With the default hash table size of 211, the same file takes just 821 ms instead of 2032 ms, not bad. With the table size of 99991 this boost vanishes though — the shortest duration is 181 ms. With the size of 10007 it is 199 ms — i.e. still visible (compared to 227 ms with the old `grow.c` code). So I think I will backport this new code to our repo and use the hash table size of 49999 for now. I will try the full run to see how well it behaves. Note that the HLL code also uses one hash table of the same size. We should consider it when estimating total memory consumption of one EMXOMFLD process.

Note that `weakld.c` also maintains two its own hash tables (for global symbols and for exported symbols) which now have the same size of 211. I will make them 49999 too.

Together, this will cost additional 800 KB (50K * 4 * 4) of memory per each EMXOMFLD process. I think we can afford that.

Steven, yes, I will consider your suggestions as well, didn't come to that part yet. I guess I won't bother myself with calculating this ratio to check the existing function but just look for a decent string hash impl on the Internet (I recall I recently did that for something already). `weakld.c` uses a djb2 variant and what `grow.c` seems to use the sdbm one (see e .g. http://www.cse.yorku.ca/~oz/hash.html). I guess it makes sense to change it to djb2 as well as the author claims it's the fastest. But I will do some more research on that.

**Comment by dmik** [comment]
Increasing `weakld.c` hash table sizes to 49999 brings the above file's timing down to just 22 ms at best. This is amazing!

**Comment by dmik** [comment]
If I'm reading the results of my full run correctly, EMXOMFLD spent only 5 minutes (!!!) to prepare everything fro WL.EXE — as opposed to hours it took before. Now WL.EXE is running (and this will most likely crash). But it's easy to debug WL.EXE now given how fast EMXOMFLD works now.

**Comment by dmik** [comment]
Some clarifications. First, the full run completes in just 2 min 40 sec here with both hash tables sized as 49999. Pretty fast! Increasing them both to 99991 drops it down to 2 min 5 sec but it doubles memory consumption so I don't really think it's worth.

Second, the maximum size of hash tables at any given time is not 800 KB. There is one table per each EMXOMF invocation (i.e. 200 KB). And then three tables per each EMXOMFLD invocation (i.e. 600 KB) but these tables are freed **before** calling WL (which also needs A LOT of memory) so it's actually not very important how big they are. It's very unlikely that there will be more than one EMXOMFLD process (followed by WL) anyway.

Third, lowering down the `strpool` table to 19997 makes each EMXOMF invocation only need 20 * 4 = 80 KB of memory but it slows down EMXOMFLD time (which also uses this table) to 3 min 5 sec. I didn't profile EMXOMF performance but I think it will also degrade. However, a difference of 120 KB between 19997 and 49999 hash tables doesn't look significant given that huge object files eat up hundreds of megabytes of memory (1 GB is not unusual in debug builds Chromium, that's why I limited ninja parallelism to just 3 processes for now).

All in all, I will just leave both tables at 49999.

Forth, @StevenLevine, your speed up suggestions from https://github.com/bitwiseworks/libc/issues/83#issuecomment-646868587 don't make any difference even for the full run (at least it's not measurable) so I will postpone them for some other time. Note that I didn't try reusing the hash actually (because there are two different hash functions and I'm not going to make them one now) but I don't suspect this change to be significant either. I don't want to break things by too intrusive changing in the situation of the lack of time.
